#!/bin/bash

if [ "$1" == "" ]; then 
	echo "Please input a file path"
	exit 0
fi

file=$1
extension="${file##*.}"

if [ "$extension" != "desktop" ]; then
	echo "Wrong file extension, please try again on a desktop file"
	exit 0
fi

if grep -q Hidden=true "$file"; then
	echo "File is already hidden. Please try again on a desktop file that isn't hidden"
	exit 0
fi

if grep -q Hidden=false "$file"; then
	sed -i 's/false/true/g' $file
	echo "File is now hidden."
	exit 0
fi

echo "Hidden=true" >> $file
echo "File is now hidden"
exit 0
